image: ubuntu

stack: python 3.7.0

cache:
    - /home/appveyor/.cache/pip/wheels/

install:
    - python --version
    - git submodule init
    - git submodule update
    - python -m pip install --upgrade pip wheel setuptools
    - python -m pip install --upgrade -r .ci/requirements.txt

build_script:
    - make
    - pip install -e .

test_script:
    - make test
    - make debug
    - make test
